### ISSUE TITLE
Model Diverge!

### ISSUE THREAD

**Issue by AboMad** [jalola/improved-wgan-pytorch#16]
Hi There,
I have tried to reproduce the results of WGAN-gp based on your implementation on ImageNet (64x64)  [(http://image-net.org/small/download.php)](url), but I found this error:

> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

SO, I tried to avoid it by setting: 
`torch.backends.cudnn.enabled = False`
Then It works with batch_size =32 (64 raised a memory issue). 

However, for 2700 iteration, the model diverged!. Is it related to that change in code?

System info:
Windows 10
Pytorch 1.4
cuda 10.1, V10.1.243
cudnn 6.14

**Comment by jalola** [comment]
Hi,

There is an issue going on with Pytorch 1.4 here
https://github.com/pytorch/pytorch/issues/32395

Better to use Pytorch 1.2 as in requirements.txt or you install Pytorch 1.4 nightly.
You can use docker container to train right? it is safer to install stuff there.
If you use Pytorch 1.2, there are many docker images out there already installing what you need to train. For example, this one: `pytorch/pytorch:nightly-devel-cuda10.0-cudnn7`

**Comment by jalola** [comment]
feel free to open it again if you still have this issue
