### ISSUE TITLE
cant work ：RuntimeError: shape '[32, 3, 96, 96]' is invalid for input of size 580608

### ISSUE THREAD

**Issue by FZUczh** [jalola/improved-wgan-pytorch#17]

**Comment by jalola** [comment]
I think you need to use dim of images as the power of 2 such as 32, 64, 128. The repo is tested with dim 64.

**Comment by FZUczh** [comment]
> I think you need to use dim of images as the power of 2 such as 32, 64, 128. The repo is tested with dim 64.

ok,thank you

**Comment by jalola** [comment]
Otherwise, you need to change the code in the Discriminator and Generator network

**Comment by FZUczh** [comment]
> Otherwise, you need to change the code in the Discriminator and Generator network

OK,it has worked just now.Thank you for your reply
