### ISSUE TITLE
Questions about noise

### ISSUE THREAD

**Issue by ZhiyuanLck** [jalola/improved-wgan-pytorch#19]
Hello, thanks much for your code! I have two questions here about noise:
In code of calculation of `gen_cost`, why noise requires grad?
```py
          noise.requires_grad_(True)
```
And in the later code when training G, why
```py
            with torch.no_grad():
                noisev = noise  # totally freeze G, training D
```
can freeze G?

**Comment by jalola** [comment]
Hi, thanks for that point

I think it is a bug.
with torch.no_grad():
       noisev = noise 
if noise.requires_grad==True then noisev.requires_grad is still ==True

Anyway, gen_rand_noise just randoms a noise with requires_grad==False, so luckily the code still works as expected.

We should remove that line and replace with explicit set noise.requires_grad_(False)
