### ISSUE TITLE
Backward

### ISSUE THREAD

**Issue by NUS-Tim** [jalola/improved-wgan-pytorch#22]
I noted that you only use one backward() when training D, and many authors use two, how do u think about it?

**Comment by jalola** [comment]
Hi Tim,
Can you share an example?

**Comment by NUS-Tim** [comment]
Yes, I mean, in your fils, let's see in congan_train.py, when training G, you use only one backward(), which is g_cost.backward(), and when training D, there is also only one (disc_cost + ACGAN_SCALE*disc_acgan).backward(). But I had seen many others' codes that do 3 backwards(), I modify my code based on their code and find that the GAN does not work, so I'm not sure is where the problem is. The problem link can be found here: https://stackoverflow.com/questions/69116199/wgan-loss-always-increase. If you have free time, you may check it, thx a lot! Note that this is WGAN and contain 2 backwards, if it is WGAN-GP, there should be one more GP backwards......

**Comment by jalola** [comment]
You mean here?
https://github.com/jalola/improved-wgan-pytorch/blob/master/train.py#L192

`disc_cost = disc_fake - disc_real + gradient_penalty`
`disc_cost.backward()`

This equals:

`disc_fake.backward()`
`(-disc_real).backward()`
`gradient_penalty.backward()`

**Comment by NUS-Tim** [comment]
Thx, it seems I still cannot find the problem... I think my network is all OK...
