### ISSUE TITLE
Regarding conditioning in the generator

### ISSUE THREAD

**Issue by furkanulger** [jalola/improved-wgan-pytorch#24]
Dear jalola,

Thank you for your enlightening repository on conditional WGAN-GP. I am particularly interested in the conditional part to generate better images compared to the unconditional version.  In other repositories, people concatenate label embedding to the noise vector that are at the same size. For example, say, the noise vector is 640 dimensional, we end up with [batch size, 1280] dimensional matrix after concatenating the embedding and noise vector. Then pass it through the network. However, I realized that you replace first c columns with the class labels where c is the number of classes. Is there any theoretical justification for that or references? Thanks in advance.

**Comment by jalola** [comment]
Hi @furkanulger ,

Apology for late response. The theory and implementation we learn from here: https://github.com/clvrai/ACGAN-PyTorch
I added it into acknowledgement.
