### ISSUE TITLE
about the size of images

### ISSUE THREAD

**Issue by ZackSoul** [jalola/improved-wgan-pytorch#29]
Hello, I want to ask if your picture supports the size of 32 * 32, and how about the training effect

**Comment by jalola** [comment]
Hi
This may support 32x32, you can pass the dim here https://github.com/jalola/improved-wgan-pytorch/blob/master/train.py#L39

I didn't train with the size other than 64 so I am not sure with 32. Please let us know the result of 32 in case you will train it

Thanks
