### ISSUE TITLE
Some question in model.py

### ISSUE THREAD

**Issue by kangwang17** [jalola/improved-wgan-pytorch#5]
i don't know the function of "class DepthToSpace(nn.Module):", can you give me a brief introduction, thank you !

**Comment by jalola** [comment]
Hi,

Because Pytorch did/does not have this function so I wrote it myself.
The function is a transformation of depth dimension of a tensor into blocks.

The original description is from Tensorflow documentation. Please check it here:
https://www.tensorflow.org/api_docs/python/tf/depth_to_space

**Comment by kangwang17** [comment]
Thank you for your answering!!! I get it!

在2018-11-03 20:22:52，Hung Nguyennotifications@github.com写道：

Hi,

Because Pytorch did/does not have this function so I wrote it myself.
The function is a transformation of depth dimension of a tensor into blocks.

The original description is from Tensorflow documentation. Please check it here:
https://www.tensorflow.org/api_docs/python/tf/depth_to_space
