### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by RomanSteinberg** [jalola/improved-wgan-pytorch#7]
It is impossible to run script `gan_train.py` because it has missing classes like `DCGANDiscriminator` and missing scripts like `models.dcgan`. 

Also, I suggest to write `config.yaml` and use smaller datasets for base example (it is very painful to download 42Gb to verify if this source code works or not).

**Comment by jalola** [comment]
hi,

The dcgan was some old experiment and we didn't remove it when pushing the code . Basically, there is only one mode which is the wgan-gp, so I just removed all unnecessary stuffs (dcgan, MODE....).

Yeh right, we should have put smaller dataset such as imagenets. Anyway, you can change it to any image dataset (imagenet or your own one) as we put some notes here: https://github.com/jalola/improved-wgan-pytorch/blob/master/gan_train.py#L34
Hope it helps
