### ISSUE TITLE
A question about loss_G.backward(Mone)

### ISSUE THREAD

**Issue by EliotChenKJ** [jalola/improved-wgan-pytorch#9]
First, i have to thank for your sharing of this work, it does help me understanding the wgan-gp better, but here is a little question:

- what does the Mone in the loss_G.backward() mean?

l've just got to know wgan-gp recently, so hope the author can help me with this question.

**Comment by jalola** [comment]
Hi,
Thanks for asking, basically mone is minus one tensor.
So in the loss, this is the same to:
`gen_cost = -gen_cost`
`gen_cost.backward()`

You can check this issue:
https://github.com/jalola/improved-wgan-pytorch/issues/1

**Comment by EliotChenKJ** [comment]
Ok, now i understand its meaning. Thank for ur answer~
